export const DATA = {
  name: 'NGUYEN HOAI NAM',
  title: 'Full-stack Developer',
  contact: [
    { icon: '📞', value: '0383337842', href: 'tel:0383337842' },
    { icon: '✉️', value: 'namxg1@gmail.com', href: 'mailto:namxg1@gmail.com' },
    { icon: '🌐', value: 'github', href: 'https://github.com/hoainambeco' },
    {
      icon: '💼',
      value: 'linkedin',
      href: 'https://www.linkedin.com/in/namnguyen1024/',
    },
    { icon: '📍', value: 'Ha Noi, Viet Nam' },
  ],
  about: `Driven by the challenge of building end-to-end products, I work as a Full-Stack Engineer with experience across modern frontend, scalable backend systems, and blockchain technologies. I focus on writing clean, maintainable code while optimizing performance and system reliability. Alongside full-stack development, I actively explore blockchain, with the goal of growing into a senior role where I can combine technical depth with strategic impact.`,
  education: [
    {
      year: '2020 – 2025',
      school: 'University of Transport and Communications — UTC',
      degree: 'Bachelor of Information Technology',
      grade: 'Good degree',
      accent: true,
    },
    {
      year: '2020 – 2022',
      school: 'FPT Polytechnic College',
      degree: 'Mobile programming',
      grade: 'Honors Degree',
      accent: false,
    },
  ],
  skills: [
    {
      category: 'Back-end',
      accent: false,
      tags: [
        'Node.js',
        'NestJS',
        'Express',
        'Microservices',
        'WebSockets',
        'GraphQL',
        'REST API',
        'Bull Queue',
        'Kong Gateway',
        'Kafka',
        'S3',
      ],
      desc: '3+ years building production-grade APIs and distributed systems with Node.js (NestJS, Express). Proficient in designing Microservices architectures with clean service boundaries and independent deployability. Implemented Event-Driven patterns using Kafka (Saga, CQRS) for reliable async communication across services. Built real-time bidirectional features with WebSockets and managed background job pipelines via Bull queue and AWS S3.',
    },
    {
      category: 'Front-end',
      accent: true,
      tags: [
        'React.js',
        'Next.js',
        'TypeScript',
        'Redux',
        'TailwindCSS',
        'Telegram MiniApp',
        'Ethers.js',
        'Web3.js',
        'Solidity',
        'Aptos',
      ],
      desc: 'Built responsive SPA/SSR interfaces with React.js and Next.js. Integrated Web3 wallet connections and on-chain interactions using Ethers.js and Web3.js. Developed and deployed Smart Contracts on BNB Chain and Aptos/Movement.',
    },
    {
      category: 'Database',
      accent: false,
      tags: [
        'PostgreSQL',
        'MySQL',
        'MongoDB',
        'Redis',
        'Oracle',
        'Elasticsearch',
      ],
      desc: 'Designed schemas across relational (PostgreSQL, MySQL, Oracle) and NoSQL (MongoDB) databases. Implemented Redis Cluster for high-availability caching. Migrated search from Solr to Elasticsearch with multi-database synchronization.',
    },
    {
      category: 'DevOps',
      accent: true,
      tags: [
        'Docker',
        'GitHub Actions',
        'AWS (EC2, ECR, CloudWatch)',
        'Linux',
        'Nginx',
      ],
      desc: 'Containerized applications with Docker and managed CI/CD pipelines via GitHub Actions and GitLab Runner. Deployed and monitored services on AWS (EC2, ECR, CloudWatch). Configured Nginx reverse proxies and Kong API Gateway for traffic management.',
    },
    {
      category: 'English',
      accent: false,
      tags: ['B1 English Certification'],
      desc: 'Holds B1 English Certification. Comfortable reading technical documentation, writing clear code comments, and collaborating in English-language environments.',
    },
  ],
  experience: [
    {
      company: 'SOTATEK JSC',
      period: '04/2026 – Present',
      role: 'Software Engineer',
      accent: true,
      bullets: [
        'I am currently employed at SotaTek, specializing in delivering high-quality software outsourcing solutions for Japanese enterprises.',
        'At SotaTek, I am responsible for developing and managing outsourcing projects, ensuring we meet the strict standards and requirements of our Japanese clients.',
      ],
      tech: [
        'NestJS',
        'PostgreSQL',
        'Kafka',
        'Redis Cluster',
        'Elasticsearch',
        'Docker',
        'Solidity',
        'AWS',
        'React.js',
        'Next.js',
      ],
    },
    {
      company: 'IGB SOFT JSC',
      period: '04/2025 – 04/2026',
      role: 'Backend Engineer',
      accent: false,
      bullets: [
        'Migrating legacy PHP systems to Microservices architecture using NestJS, Kafka, and Redis.',
        'Optimizing API performance and system stability for a large-scale recruitment platform.',
      ],
      tech: [
        'NestJS',
        'PostgreSQL',
        'Kafka',
        'Redis (Cluster)',
        'Elasticsearch',
        'Docker',
      ],
    },
    {
      company: 'DATH SOLUTIONS JSC',
      period: '07/2024 – 04/2025',
      role: 'Fullstack & Blockchain Developer',
      accent: true,
      bullets: [
        'Developed SocialFi platforms and Telegram MiniApps with real-time features.',
        'Built and deployed Smart Contracts on BNB Chain and Aptos.',
      ],
      tech: [
        'NestJS',
        'Next.js',
        'Solidity',
        'Web3',
        'PostgreSQL',
        'AWS',
        'GitHub Actions',
      ],
    },
    {
      company: 'BYTESOFT VIETNAM JSC',
      period: '06/2022 – 07/2024',
      role: 'Backend Engineer',
      accent: false,
      bullets: [
        'Developed business operation software (BOffice) focusing on recruitment and timekeeping modules.',
        'Implemented RESTful APIs, GraphQL, and WebSockets for international markets.',
      ],
      tech: ['NestJS', 'React.js', 'MySQL', 'MongoDB', 'Docker', 'CI/CD'],
    },
  ],
  projects: [
    {
      name: 'Careerviet',
      sub: 'Recruitment Platform',
      period: '04/2025 – Present',
      link: 'https://careerviet.vn/',
      accent: false,
      bullets: [
        'Designed and led migration of a large-scale PHP monolith to NestJS Microservices, improving service isolation and independent deployability.',
        'Implemented Event-Driven Architecture with Kafka + Saga Pattern to guarantee distributed transaction consistency across heterogeneous databases (PostgreSQL, MongoDB, Oracle PL/SQL).',
        'Boosted search performance by migrating from Solr to Elasticsearch with real-time multi-database synchronization.',
        'Enforced high-availability caching via Redis Cluster and centralized API traffic management through Kong Gateway.',
      ],
      tech: [
        'NestJS',
        'Microservices',
        'Kafka (Saga)',
        'Redis Cluster',
        'Elasticsearch',
        'PostgreSQL',
        'MongoDB',
        'Oracle PL/SQL',
        'Kong Gateway',
        'Docker',
      ],
    },
    {
      name: 'Acanet',
      sub: 'SocialFi & Telegram MiniApp',
      period: '07/2024 – 04/2025',
      award: '🏆 Runner-up – Movement Olympus Hackathon',
      accent: true,
      bullets: [
        'Engineered a SocialFi network and Telegram mini-app to automate and manage high-volume airdrop campaigns.',
        'Developed and deployed Smart Contracts on BNB Chain and Aptos/Movement using Solidity.',
        'Built real-time communication features using WebSockets and managed background jobs with Bull queue to optimize token distribution.',
      ],
      tech: [
        'NestJS',
        'Next.js',
        'Solidity',
        'Web3',
        'PostgreSQL',
        'OpenSearch',
        'AWS (EC2, ECR, S3)',
      ],
    },
    {
      name: 'BOffice',
      sub: 'Business Management',
      period: '07/2022 – 07/2024',
      link: 'https://boffice.bytesoft.vn/',
      accent: false,
      bullets: [
        'Developed core modules for recruitment, timekeeping, and library functions for both domestic and international markets.',
        'Implemented real-time updates using WebSockets and established a robust API documentation system with Swagger.',
        'Managed application deployment and server infrastructure using Docker, Nginx, and GitLab Runner.',
      ],
      tech: [
        'NestJS',
        'MySQL',
        'Redis',
        'WebSockets',
        'React.js',
        'Docker',
        'Nginx',
        'Ubuntu',
      ],
    },
    {
      name: 'Bvote',
      sub: 'Online Voting Platform',
      period: '10/2022 – 12/2024',
      link: 'https://bvote.vn/',
      accent: true,
      bullets: [
        'Developed a secure online General Meeting of Shareholders (GMS) platform utilizing the MERN stack to ensure transparency and high availability during voting sessions.',
        'Engineered a Robust Role-Based Access Control (RBAC) system and administrative modules for efficient shareholder data management and election content configuration.',
        'Implemented real-time voting updates and live communication features using Socket.io and WebSockets to handle concurrent user interactions.',
        'Managed application deployment on custom-built servers using Docker, Nginx, and GitLab Runner for automated CI/CD processes.',
      ],
      tech: [
        'MongoDB',
        'Express.js',
        'React.js',
        'Redux',
        'Node.js',
        'Socket.io',
        'Redis',
        'Docker',
        'Nginx',
      ],
    },
  ],
  award: 'Runner-up – Movement Olympus Hackathon',
  awardLink:
    'https://movementlabs.notion.site/Olympus-Hackathon-Finalists-588d4533f53a4a32b0a67f7cb9846452',
};
